GeeksNegar/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
 
]

# SET STATIC URLS :
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

accounts/urls.py
from django.conf.urls import url

from . import views

app_name= 'accounts'
urlpatterns = [
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
    url(r'^profile/$', views.ProfileView, name='profile'),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]+)$', views.ProfileViewOther, name='profile-other'),
    url(r'^profile/edit-profile/$', views.ProfileEdit, name='profile-edit'),
    url(r'^profile/add-post/$', views.addPost, name='add-post'),
    url(r'^profile/edit-profile/profile-pic-change/$', views.prfilepicchange, name='profile-pic'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)$', views.ProfileViewOther, name='profile-other'),
    #url(r'^profile/post/create/$', views.ProfilePostCreat, name='PostCreat'),
    #url(r'^profile/post/(?P<pk>\d+)/update/$', views.ProfilePostUpdate, name='PostUpdate'),
    #url(r'^profile/post/(?P<pk>\d+)/delete/$', views.ProfilePostDelete, name='PostDelete '),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]+)$', views.ProfileViewOther, name='profile-other'),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]+)/profile-pic-change/$', views.prfilepicchange, name='profile-pic')
]

blog/urls.py
from django.conf.urls import url
from . import views                                  #importing views of this app to joind them to URLS

app_name= 'blog'                                     #to find app's url better and faster

urlpatterns = [
    url(r'^$', views.index , name='index' ), #we used as_view() function to reach Index class of our view
    url(r'^(?P<post_id>[0-9]+)$', views.post_detail , name='post-detail' ),
    url(r'^(?P<post_id>[0-9]+)/add-comment/$', views.comment_handler , name='post-like-handle' ),
    url(r'^aparat/', views.aparat , name='aparat' )
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms

class ProfilePicForm(forms.Form):
    pic = forms.ImageField()

class AddPostForm(forms.Form):
    title = forms.CharField(label="Title:",widget=forms.TextInput(attrs={'class' : 'form-control'}))
    caption = forms.CharField(label="Caption:",widget=forms.Textarea(attrs={'class' : 'form-control'}))

accounts/views.py
from django.shortcuts import render, get_object_or_404,HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from blog import models
from .forms import *
from django.contrib.auth.decorators import login_required

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:profile')
    template_name = 'accounts/signup.html'

    def generate_invoice(self):
        print("hi")
        custom_user, created = models.CustomUser.objects.get_or_create( user=self.object )
        custom_user.save()
        return 1

@login_required
def ProfileView(request):
    post_list =  models.Post.objects.all()
    custom_user, created = models.CustomUser.objects.get_or_create( user=request.user )
    user_posts=[]
    form_post = AddPostForm
    for post in post_list:
        for member in post.member.all():
            if request.user==member.user.user:
                user_posts.append(post)
    context={
        'post_list':user_posts,
        'custom_user':custom_user,
        'form_post':form_post,
    }
    return render(request, 'accounts/profile.html',context=context)


@login_required
def ProfileEdit(request):
    custom_user, created = models.CustomUser.objects.get_or_create( user=request.user )
    form = ProfilePicForm
    context={
        'form':form,
        'custom_user':custom_user,
    }
    return render(request, 'accounts/profile_edit.html',context=context)

def ProfileViewOther(request,username):
    user = get_object_or_404(models.User, username=username)
    post_list =  models.Post.objects.all()
    custom_user, created = models.CustomUser.objects.get_or_create( user=user )
    custom_post_list =  models.CustumPost.objects.all().filter(user=user)
    user_posts=[]
    for post in post_list:
        print(post.member.all())
        for member in post.member.all():
            if user==member.user.user:
                user_posts.append(post)
    context={
        'custom_post_list':custom_post_list,
        'custom_user':custom_user,
        'user_other':user,
        'post_list':user_posts,
    }
    return render(request, 'accounts/profile_other.html',context=context)

def prfilepicchange(request):
    # if this is a POST request we need to process the form data\
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ProfilePicForm(request.POST, request.FILES)
        #print(request.FILES['pic'])
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            pic_file = request.FILES['pic']
            custom_user, created = models.CustomUser.objects.get_or_create( user=request.user )
            custom_user.profile_pic = pic_file
            custom_user.save()
            # redirect to a new URL:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProfilePicForm()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def addPost(request):
     # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = AddPostForm(request.POST)
        if form.is_valid():
            form_title = form.cleaned_data['title']
            form_text = form.cleaned_data['caption']
            post = models.CustumPost.objects.create(user=request.user,title=form_title,text=form_text)
            post.save()
            custumPost_list= models.CustumPost.objects.all()

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AddPostForm()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

accounts/templates/accounts/profile.html
{% extends 'blog/base.html' %}
{% load static %}
{% block extraCss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'css/post_index.css' %}" />
{% endblock %}


{% block title %}Profile{% endblock %}

{% block content %}
<div class="container" style="margin-top: 50px;">
  {% if user.is_authenticated %}

  <center>
    <div>
      <div class="picture-container">
        <div class="profilepic">
          <img src="{{ custom_user.profile_pic.url }}" class="profilepic" id="wizardPicturePreview" title=""/>
        </div>
      </div>
    </div>
  </center>
  <div>
    <center><h2>Hello {{ user.get_username }}!</h2>
      <a href="{% url 'accounts:profile-edit' %}">Edit Profile</a><br>

    </center><hr/>

  </div>

  <div class="container">
    <div>
      <center>
        <h3>Add New Twit</h3>
        
      </center>
  
    </div>
    <form action="{% url 'accounts:add-post' %}" method="post">
      {% csrf_token %}
      {{ form_post }}
      <input type="submit" value="Add Post" class="btn btn-dark" style="width: 100%;">
    </form>

  </div>
  <hr/>
  <div>
    <h3><i class="fa fa-file"></i> Posts you are a member of that</h3><hr/>
  </div>
  <div class="container" style="margin-bottom: 30px;">

    <div class="row" style="margin-top: 50px;">
      {% if post_list %}
      {% for post in post_list %}
      {% if post.published %}
      <div class="col-sm-4" >

        <div class="item-box-blog" >
          <div class="item-box-blog-image">
            <!--Date-->
            <div class="item-box-blog-date bg-blue-ui white"> <span class="mon">{{post.pub_date}}</span> </div>
            <!--Image-->
            {% if post.image is not None %}
            <figure> <img src="/media/{{post.image}}" width="100%" height="300px;"> </figure>
            {% endif %}

            {% if post.video is not None %}
            <figure> <video width="100%" height="300px;" controls><source src="/media/{{post.video}}" type="video/mp4"></video> </figure>
              {% endif %}

            </div>
            <div class="item-box-blog-body">
              <!--Heading-->
              <div class="item-box-blog-heading">
                <a href="../../blog/{{post.id}}" tabindex="0" style="color:rgb(128, 0, 0);">
                  <h5>{{post.title}}</h5>
                </a>
              </div>
              <!--Data-->
              <div class="item-box-blog-data" style="padding: px 15px;">
                <p><i class="fa fa-user-o"></i> Admin, <i class="fa fa-comments-o"></i> Comments({{ post.comments.all|length }})</p>
              </div>
              <!--Text-->
              <div class="item-box-blog-text">
                <p>{{post.text}}</p>
              </div>
              <div class="mt"> <a href="../../blog/{{post.id}}" tabindex="0" class="btn bg-blue-ui white read">read more</a> </div>
              <!--Read More Button-->
            </div>
          </div>

          <!-- <div class="thumbnail">
          <a href="{{post.id}}">
          <div><h2>{{ post.title }}</h2></div>
          <div><h5>{{ post.pub_date }}</h5></div><br>
          {% if post.video is not None %}
          <div><video width="100%" height="100%" controls><source src="/media/{{post.video}}" type="video/mp4"></video></div>
          <div class="caption"><h5>{{ post.text }}</h5></div><br>
          {% endif %}
          {% if post.image is not None %}
          <div><img src="/media/{{post.image}}" width="100%" height="100%"></div>
          <div><h5>{{ post.text }}</h5></div><br>
          {% endif %}
          {% if post.image is None and post.video is None %}
          <div><h5>{{ post.text }}</h5></div><br>
          {% endif %}
          <hr/>
          {% endif %}
        </a>
      </div> -->
    </div>
    {% endfor %}
    {% else %}
    <p>No posts are available.</p>
    {% endif %}
  </div>
</div>
{% endif %}

</div>
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'blog/base.html' %}
{% load static %}
{% block extraCss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'css/post_index.css' %}" />
{% endblock %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="container" style="margin-top: 50px;">
{% if user.is_authenticated %}                          

    <center>
    <div>
      <div class="picture-container">
        <div class="profilepic">
            <img src="{{ custom_user.profile_pic.url }}" class="profilepic" id="wizardPicturePreview" title=""/>
        </div>
    </div>
    </div>
  </center>
    <div>
        <center><h2>Hello {{ user.get_username }}!</h2>
        </center><hr/>
    </div>
    <div class="row">
        <div class="col-lg-6">
          <h3>Change Profile Picture : </h3>
        </div>
        <div class="col-lg-6">
        <form class="form-group" action="profile-pic-change/" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for non_field_error in form.non_field_errors %}
              <p class="alert alert-danger">{{ non_field_error }}</p>
          {% endfor %}
          <div class="row">
          {% for field in form %}
              <div>
                  {{ field }}
              {% for error in field.errors %}
                  <p class="alert alert-danger">{{ error }}</p>
              {% endfor %}
              </div>
          {% endfor %}
          <div>
          <input type="submit" value="change" class="btn btn-light">
        </div>
      </div>
        </form>
      </div>
      
    </div>
    <hr/>
{% endif %}

</div>
{% endblock %}

accounts/templates/accounts/profile_other.html
{% extends 'blog/base.html' %}
{% load static %}
{% block extraCss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'css/post_index.css' %}" />
{% endblock %}

{% block title %}{{ user_other.get_username }} - Profile{% endblock %}

{% block content %}
<div class="container" style="margin-top: 50px;">
    <center>
    <div>
      <div class="picture-container">
        <div class="profilepic">
            <img src="{{ custom_user.profile_pic.url }}" class="profilepic" id="wizardPicturePreview" title=""/>
        </div>
    </div>
    </div>
  </center>
    <div>
        <center><h2>{{ user_other.get_username }}!</h2>
        </center><hr/>
    </div>

    <div>
      <h3><i class="fab fa-twitter"></i> {{ user_other.get_username }} Twitts</h3><hr/>
    </div>

    <div class="container" style="margin-bottom: 30px;">

      <div class="row" style="margin-top: 50px;">
        {% if custom_post_list %}
        {% for custom_post in custom_post_list %}
        <div class="col-sm-4" >

          <div class="item-box-blog" >
              <div class="item-box-blog-body">
                <!--Heading-->
                <div class="item-box-blog-heading">
                  <a href="../../blog/{{post.id}}" tabindex="0" style="color:rgb(128, 0, 0);">
                    <h5>{{custom_post.title}}</h5>
                  </a>
                </div>
              <!--Text-->
              <div class="item-box-blog-text">
                <marquee>{{custom_post.text}}</marquee>
              </div>
              <!--Read More Button-->
            </div>
          </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No twitts are available.</p>
    {% endif %}
    </div>
      </div>


    <div>
        <h3><i class="fa fa-file"></i> Posts {{ user_other.get_username }} is a member of that</h3><hr/>
    </div>


    <div class="container" style="margin-bottom: 30px;">

      <div class="row" style="margin-top: 50px;">
        {% if post_list %}
        {% for post in post_list %}
        {% if post.published %}
        <div class="col-sm-4" >

          <div class="item-box-blog" >
            <div class="item-box-blog-image">
              <!--Date-->
              <div class="item-box-blog-date bg-blue-ui white"> <span class="mon">{{post.pub_date}}</span> </div>
              <!--Image-->
              {% if post.image is not None %}
              <figure> <img src="/media/{{post.image}}" width="100%" height="300px;"> </figure>
              {% endif %}

              {% if post.video is not None %}
              <figure> <video width="100%" height="300px;" controls><source src="/media/{{post.video}}" type="video/mp4"></video> </figure>
                {% endif %}

              </div>
              <div class="item-box-blog-body">
                <!--Heading-->
                <div class="item-box-blog-heading">
                  <a href="../../blog/{{post.id}}" tabindex="0" style="color:rgb(128, 0, 0);">
                    <h5>{{post.title}}</h5>
                  </a>
                </div>
                <!--Data-->
                <div class="item-box-blog-data" style="padding: px 15px;">
                <p><i class="fa fa-user-o"></i> Admin, <i class="fa fa-comments-o"></i> Comments({{ post.comments.all|length }})</p>
              </div>
              <!--Text-->
              <div class="item-box-blog-text">
                <p>{{post.text}}</p>
              </div>
              <div class="mt"> <a href="../../blog/{{post.id}}" tabindex="0" class="btn bg-blue-ui white read">read more</a> </div>
              <!--Read More Button-->
            </div>
          </div>

          <!-- <div class="thumbnail">
          <a href="{{post.id}}">
          <div><h2>{{ post.title }}</h2></div>
          <div><h5>{{ post.pub_date }}</h5></div><br>
          {% if post.video is not None %}
          <div><video width="100%" height="100%" controls><source src="/media/{{post.video}}" type="video/mp4"></video></div>
          <div class="caption"><h5>{{ post.text }}</h5></div><br>
          {% endif %}
          {% if post.image is not None %}
          <div><img src="/media/{{post.image}}" width="100%" height="100%"></div>
          <div><h5>{{ post.text }}</h5></div><br>
          {% endif %}
          {% if post.image is None and post.video is None %}
          <div><h5>{{ post.text }}</h5></div><br>
          {% endif %}
          <hr/>
          {% endif %}
        </a>
      </div> -->
    </div>
    {% endfor %}
    {% else %}
    <p>No posts are available.</p>
    {% endif %}
    </div>
      </div>

</div>
{% endblock %}

accounts/templates/accounts/signup.html
<!doctype html>
{% load static %}

{% block content %}
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>GeeksNegar - Sign Up</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<!--     Fonts and icons     -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">

	<!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/gsdk-bootstrap-wizard.css' %}" rel="stylesheet" />

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link href="{% static 'css/demo.css' %}" rel="stylesheet" />
</head>

<body>
<div class="image-container set-full-height" style="background-image: url('../../../media/img/cyberpunk-3849.jpg');  background-repeat: no-repeat;
background-attachment: fixed;">
    <!--   Creative Tim Branding   -->
    <a href="../../blog">
         <div class="logo-container">
            <div class="logo">

            </div>
            <div class="brand">
                GeeksNegar
            </div>
        </div>
    </a>


<!--   Big container   -->
<div class="container">
  <div class="row">
  <div class="col-sm-8 col-sm-offset-2">

      <!--      Wizard container        -->
      <div class="wizard-container">

          <div class="card wizard-card" data-color="red" id="wizardProfile">
          <!--        You can switch ' data-color="orange" '  with one of the next bright colors: "blue", "green", "orange", "red"          -->

                <div class="wizard-header">
                    <h3>
                       <b>SIGNUP </b>TO GEEKSNEGAR <br>
                    </h3>
                </div>
<!--
      <div class="wizard-navigation">
        <ul>
                        <li><a href="#about" data-toggle="tab">Sign up</a></li>
                        <li><a href="{% url 'login' %}">Login</a></li>
                    </ul>

      </div> -->
      <hr/>


        
                  <div class="tab-content" style="margin-left:50px;width: 500px;">

                      <div class="form-group" id="about">
                        <div class="row">
                            <div class="container">
                            </div>
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button class="btn btn-primary" type="submit">Sign up</button>
                                
                                </form>
                        </div>
                      </div>
                    

                  </div>
          </div>
        
      </div> <!-- wizard container -->
  </div>
  </div><!-- end row -->
</div> <!--  big container -->


</div>

</body>

	<!--   Core JS Files   -->
	<script src="{% static 'js/jquery-2.2.4.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.bootstrap.wizard.js' %}" type="text/javascript"></script>

	<!--  Plugin for the Wizard -->
	<script src="{% static 'js/gsdk-bootstrap-wizard.js' %}"></script>

	<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
	<script src="{% static 'js/jquery.validate.min.js' %}"></script>

</html>
{% endblock %}

accounts/templates/accounts/signup_temp.html
{% extends 'blog/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}