GeeksNegar/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
 
]

# SET STATIC URLS :
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

accounts/urls.py
from django.conf.urls import url

from . import views

app_name= 'accounts'
urlpatterns = [
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
    url(r'^profile/$', views.ProfileView, name='profile'),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]+)$', views.ProfileViewOther, name='profile-other'),
    url(r'^profile/edit-profile/$', views.ProfileEdit, name='profile-edit'),
    url(r'^profile/add-post/$', views.addPost, name='add-post'),
    url(r'^profile/edit-profile/profile-pic-change/$', views.prfilepicchange, name='profile-pic'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)$', views.ProfileViewOther, name='profile-other'),
    #url(r'^profile/post/create/$', views.ProfilePostCreat, name='PostCreat'),
    #url(r'^profile/post/(?P<pk>\d+)/update/$', views.ProfilePostUpdate, name='PostUpdate'),
    #url(r'^profile/post/(?P<pk>\d+)/delete/$', views.ProfilePostDelete, name='PostDelete '),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]+)$', views.ProfileViewOther, name='profile-other'),
    url(r'^profile/(?P<username>[a-zA-Z0-9_]+)/profile-pic-change/$', views.prfilepicchange, name='profile-pic')
]

blog/urls.py
from django.conf.urls import url
from . import views                                  #importing views of this app to joind them to URLS

app_name= 'blog'                                     #to find app's url better and faster

urlpatterns = [
    url(r'^$', views.index , name='index' ), #we used as_view() function to reach Index class of our view
    url(r'^(?P<post_id>[0-9]+)$', views.post_detail , name='post-detail' ),
    url(r'^(?P<post_id>[0-9]+)/add-comment/$', views.comment_handler , name='post-like-handle' ),
    url(r'^aparat/', views.aparat , name='aparat' )
]

blog/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField(max_length=5000,blank=True)
    published = models.BooleanField()
    pub_date = models.DateField()
    video = models.ForeignKey('Video',on_delete=models.SET_NULL, null=True , blank = True)
    image = models.ForeignKey('Image',on_delete=models.SET_NULL , null=True , blank = True)
    member = models.ManyToManyField('TeamMember')
    #likes = models.ManyToManyField('Like',blank=True,null=True)
    comments = models.ManyToManyField('Comment',blank=True,null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('blog:post-detail',args=[str(self.id)])

class CustumPost(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular post")
    user=models.ForeignKey(User, on_delete=models.PROTECT, null=True , blank = False)
    title = models.CharField(max_length=255)
    text = models.TextField(max_length=300,blank=True)

    def __str__(self):
        return self.title

class CustomUser(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='img/profilepics/',default='img/profilepics/default-avatar.png')

class Video(models.Model):
    file = models.FileField(upload_to='videos/')

    def __str__(self):
        return str(self.file)

class Image(models.Model):
    file = models.ImageField(upload_to='img/')

    def __str__(self):
        return str(self.file)

class Slider(models.Model):
    image= models.ForeignKey('Image',on_delete=models.CASCADE, null=False, blank=False )
    header= models.CharField(max_length=50, null=False, blank=False)
    caption=models.CharField(max_length=70, null=True, blank=True)

class TeamMember(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    role = models.ManyToManyField('MemberRole')

    def __str__(self):
        roles_str = ", ".join(str(r) for r in self.role.all())
        return str(self.user.user.get_username())+' | '+roles_str

class MemberRole(models.Model):
    role = models.CharField(max_length=255)

    def __str__(self):
        return str(self.role)

class Comment(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    text = models.TextField(max_length=350,blank=False)

    def __str__(self):
        return str(self.user.user.get_username())+'->'+self.text

class Like(models.Model):
    user = models.ManyToManyField(User, related_name='likes',null=True)
    post = models.ForeignKey(Post, on_delete=models.SET_NULL,null=True)
    likecount = models.IntegerField(default=0)

    def __str___(self):
        return str(self.user.get_username())

blog/forms.py
from django import forms
    
class CommentForm(forms.Form):
    comment_text = forms.CharField(label="Your Comment",widget=forms.Textarea(attrs={'class' : 'form-control'}))

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from . import models
from .forms import *
from GeeksNegar import settings
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
############### aparat API
from django.core import serializers
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


def index(request):
    post_list =  models.Post.objects.order_by('pub_date')[:6]
    slider_list= models.Slider.objects.order_by('-id')
    custom_post_list = models.CustumPost.objects.all()[:9]
    context={'post_list' : post_list, 'slider_list' : slider_list,'custom_post_list':custom_post_list,
    }
    return render(request, 'blog/index.html',context=context)

def post_detail(request,post_id='1'):
    post_like_handle(request,post_id)
    obj = get_object_or_404(models.Post, pk=post_id)
    post_like, created = models.Like.objects.get_or_create(post=obj)
    context={'post' : obj,
            'post_like' : post_like,
            'form_cm' : CommentForm
    }
    return render(request, 'blog/post_detail.html',context=context)

def post_like_handle(request,post_id='1'):
    if request.method == 'POST':
        user = request.user
        create_id = get_object_or_404(models.Post, id=post_id)
        liked, created = models.Like.objects.get_or_create(post=create_id)
        try:
            user_liked = models.Like.objects.get(post=create_id, user=user)
        except:
            user_liked = None

        if user_liked:
            user_liked.likecount -= 1
            liked.user.remove(request.user)
            user_liked.save()
        else:
            liked.user.add(request.user)
            liked.likecount += 1
            liked.save()
        context={'post' : create_id
        }
        return render(request, 'blog/post_detail.html',context=context)


def comment_handler(request,post_id='1'):
    # if this is a POST request we need to process the form data
    obj = get_object_or_404(models.Post, pk=post_id)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            comment_text = form.cleaned_data['comment_text']
            custom_user, created = models.CustomUser.objects.get_or_create( user=request.user )
            comment, created = models.Comment.objects.get_or_create( user=custom_user , text=comment_text )
            comment.save()
            obj.comments.add(comment)
            obj.save()
            # redirect to a new URL:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CommentForm()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

#get videos from Aparat
@csrf_exempt
def aparat(request):
    pass

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = './templates/resigtration/signup.html'

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fa">
<head>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

  <meta charset="utf-8">
  <title>GeeksNegar</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  {% block extraCss %}
  {% endblock %}

</head>
<body style="background-image: url('../media/img/cyberpunk-3849.jpg');  background-repeat: no-repeat;
background-attachment: fixed;">

  {% block header %}
  {% include "blog/header.html" %}

  {% endblock %}

  {% block content %}

  {% endblock %}

  {% block footer %}
  {% include "blog/footer.html" %}
  {% endblock %}

</body>
</html>

blog/templates/blog/footer.html
<footer style="background-color:rgb(77, 0, 0);">
  <div class="container">
    <div class="row" style="color:rgb(224, 224, 209); padding-top:45px; padding-bottom:30px;">
      <div class="col-sm-4">
        <h3>Address:</h3>
        <p>University Of Guilan, Rasht, Iran</p>
      </div>
      <div class="col-sm-4">
        
        <h3>Contact Us:</h3>
        <i class="fa fa-instagram" style="font-size:36px"><a href="https://www.instagram.com/geeksnegar/" style="color:rgb(217, 217, 217); font-size:25px;">  :    @geeksnegar</a></i><br><br>
        <i class="fa fa-telegram" style="font-size:36px"><a href="https://t.me/geeksnegar" style="color:rgb(217, 217, 217); font-size:25px;">  :    @geeksnegar</a> </i><br><br>
        <a href="https://gitlab.com/amirmahdi.khosravi/geeksnegar" style="color:rgb(217, 217, 217); font-size:25px;"><i class="fa fa-gitlab" style="font-size:36px"></i>  :    Gitlab</a><br><br>
      </div>
      <div class="col-sm-4">
        <h3>About Us</h3>
        <p>GeeksNegar is a local magazine and figital art/media creation group</p>
        <p>based in university of guilan - Rasht - Iran</p>


      </div>
    </div>
  </div>
</footer>

blog/templates/blog/header.html
<nav class="navbar navbar-expand-sm navbar-dark" style=" background-color:rgb(128, 0, 0);">
  <div class="container-fluid">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="#">GeeksNegar</a>

    <!-- Links -->
    <ul class="navbar-nav" style="margin-right:700px; ">
      <li class="nav-item">
        <a class="nav-link" href="/blog/" style="color:rgb(217, 217, 217);">Home</a>
      </li>
      <li class="nav-item" >
        <a class="nav-link" href="#" style="color:rgb(217, 217, 217);" >Contact Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color:rgb(217, 217, 217);" >About Us</a>
      </li>
    </ul>
    <!-- <div class="navbar-header" style="background-color:rgb(128, 0, 0); margin: 0px 10px 0px -5px; padding-left: 10px">
    <a class="navbar-brand" href="#" style="color:rgb(224, 224, 209);" >GeeksNegar</a>
  </div>
  <ul class="nav navbar-nav">
  <li class="active" style="color:rgb(224, 224, 209);"><a href="/blog/ ">Home</a></li>
  <li ><a href="#" style="color:rgb(224, 224, 209);">contact us</a></li>
  <li><a href="#" style="color:rgb(224, 224, 209);" >about geeks</a></li>

</ul> -->
<div>
  <div class="container">
    {% if user.is_authenticated %}
    <div class="btn-group" >
      <button type="button" class="btn btn-dark" >{{ user.get_username }}</button>
      <div class="btn-group">
        <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown">
        </button>
        <div class="dropdown-menu" style="margin-left: -100px;">
          <a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a>
          <a  class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
        </div>
      </div>
    </div>
    {% else %}
    <div class="btn-group">
      <a class="btn btn-dark" href="{% url 'login'%}?next={{request.path}}" class="btn btn-primary">Login</a>
      <a class="btn btn-dark" href="{% url 'accounts:signup'%}?next={{request.path}}">Sign Up</a>
    </div>
    {% endif %}
  </div>
</div>
</div>
</nav>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block extraCss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/post_index.css' %}" />
{% endblock %}

{% block header %}
{% include "blog/header.html" %}

<div class="container-fluid" style="margin: 0px 0px 0px 0px; padding: 0px 0px 0px 0px;">
  <div id="demo" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ul class="carousel-indicators">
      {% for slides in slider_list %}
      {% if forloop.counter0 == 0 %}
      <li data-target="#demo" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
      {% else %}
      <li data-target="#demo" data-slide-to="{{ forloop.counter0 }}"></li>
      {% endif %}
      {% endfor %}
    </ul>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      {% for slides in slider_list %}
      {% if forloop.counter0 == 0 %}
      <div class="carousel-item active">
        <img src="/media/{{slides.image}}" alt="{{slides.header}}" style="width:100%; height:800px">
        <div class="carousel-caption">
          <h2>{{slides.header}}</h2>
        </div>
      </div>
      {% else %}
      <div class="carousel-item">
        <img src="/media/{{slides.image}}" alt="{{slides.header}}" style="width:100%; height:800px">
        <div class="carousel-caption">
          <h2>{{slides.header}}</h2>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
    <!-- Left and right controls -->
    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid" style="padding: 40px;color: white;">
  <h2><i class="fa fa-file"></i> Recent Posts</h2></div>
  <div class="row">

    {% if post_list %}
    {% for post in post_list %}
    {% if post.published %}
    <div class="col-sm-4" >

      <div class="item-box-blog" >
        <div class="item-box-blog-image">
          <!--Date-->
          <div class="item-box-blog-date bg-blue-ui white"> <span class="mon">{{post.pub_date}}</span> </div>
          <!--Image-->
          {% if post.image is not None %}
          <figure> <img src="/media/{{post.image}}" width="100%" height="10px;"> </figure>
          {% endif %}

          {% if post.video is not None %}
          <figure> <video width="100%" height="300px;" controls><source src="/media/{{post.video}}" type="video/mp4"></video> </figure>
            {% endif %}

          </div>
          <div class="item-box-blog-body">
            <!--Heading-->
            <div class="item-box-blog-heading">
              <a href="{{post.id}}" tabindex="0" style="color:rgb(128, 0, 0);">
                <h5>{{post.title}}</h5>
              </a>
            </div>
            <!--Data-->
            <div class="item-box-blog-data" style="padding: px 15px;">
            <p><i class="fa fa-user-o"></i> Admin, <i class="fa fa-comments-o"></i> Comments({{ post.comments.all|length }})</p>
          </div> 
          <!--Text-->
          <div class="item-box-blog-text">
            <p>{{post.text}}</p>
          </div>
          <div class="mt"> <a href="{{post.id}}" tabindex="0" class="btn bg-blue-ui white read">read more</a> </div>
          <!--Read More Button-->
        </div>
      </div>

      <!-- <div class="thumbnail">
      <a href="{{post.id}}">
      <div><h2>{{ post.title }}</h2></div>
      <div><h5>{{ post.pub_date }}</h5></div><br>
      {% if post.video is not None %}
      <div><video width="100%" height="100%" controls><source src="/media/{{post.video}}" type="video/mp4"></video></div>
      <div class="caption"><h5>{{ post.text }}</h5></div><br>
      {% endif %}
      {% if post.image is not None %}
      <div><img src="/media/{{post.image}}" width="100%" height="100%"></div>
      <div><h5>{{ post.text }}</h5></div><br>
      {% endif %}
      {% if post.image is None and post.video is None %}
      <div><h5>{{ post.text }}</h5></div><br>
      {% endif %}
      <hr/>
      {% endif %}
    </a>
  </div> -->
</div>
{% endfor %}
{% else %}
<p>No posts are available.</p>
{% endif %}
</div>
<center>
  <div style="color: white;">
    <h3><i class="fab fa-twitter"></i> Last Twitts</h3><hr/>
  </div>
</center>
  <div class="container" style="margin-bottom: 30px;">

    <div class="row" style="margin-top: 50px;">
      {% if custom_post_list %}
      {% for custom_post in custom_post_list %}
      <div class="col-sm-4" >

        <div class="item-box-blog" >
            <div class="item-box-blog-body">
              <!--Heading-->
              <div class="item-box-blog-heading">
                <a href="{% url 'accounts:profile-other' custom_post.user.get_username %}" style="color:rgb(128, 0, 0);">
                  <h5>{{custom_post.user.get_username}}</h5>
                </a> 
                <hr/>
                <div style="color:rgb(100, 100, 100);">
                  <h5>{{custom_post.title}}</h5>
                </div>
              </div>
            <!--Text-->
            <div class="item-box-blog-text">
              <marquee>{{custom_post.text}}</marquee>
            </div>
            <!--Read More Button-->
          </div>
        </div>
  </div>
  {% endfor %}
  {% else %}
  <p>No twitts are available.</p>
  {% endif %}
  </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container postdetailstyle">
{% if post %}
    {% if post.published %}
        <div><h2>{{ post.title }}</h2></div>
        <div><h5>{{ post.pub_date }}</h5></div></br>
        {% if post.video is not None %}
            <div><video width="100%" height="100%" controls><source src="/media/{{post.video}}" type="video/mp4"></video></div>
            <div><h5>{{ post.text }}</h5></div></br>
        {% endif %}
        {% if post.image is not None %}
            <div><img src="/media/{{post.image}}" width="100%" height="100%"></div>
            <div class="lead posttext"><p>{{ post.text }}</p></div></br>
        {% endif %}
        {% if post.image is None and post.video is None %}
            <div><h5>{{ post.text }}</h5></div></br>
        {% endif %}
            </hr>

        <div class="postdetailbuttons">       
        <!-- Like table -->
        <table>
            <tr>               
                <td><i class="fa fa-heart"></i>
                    <div class="badge" id="likecount">{{ post_like.likecount }}</div></td>
                {% if user.is_authenticated %}
            <!-- Like button load -->
                    {% if post_like.likecount != 0 %}
                        {% if user in post_like.user.all %}
                        <td><button type="button" class="btn btn-danger" name="{{post.id}}" id="like">Liked</button></td> 
                        {% else %}
                            <td><button type="button" class="btn btn-danger" name="{{post.id}}" id="like">Like</button></td>
                        {% endif %}
                    {% else %}
                        <td><button type="button" class="btn btn-danger" name="{{post.id}}" id="like">Like</button></td>
                    {% endif %}
                    
                    <!-- if user not logged in -->
                    {% else %}
                    <td><button type="button" class="btn btn-danger"><a href="{% url 'login' %}?next={{request.path}}">
                        Please login to like this post!</a></button></td> 
                    </tr>
                    </table>
                {% endif %}
            </tr>
            </table>
            
            <!-- AJAX Like button handle -->
            <script>
                $('#like').click(function(){
                      $.ajax({
                               type: "POST",
                               url: "{% url 'blog:post-detail' post.id %}",
                               data: {
                               'csrfmiddlewaretoken': '{{csrf_token}}'},
                               dataType: "text",
                               success: function(response) {
                                if($("#like").html() == "Like"){
                                    $("#like").html("Liked");
                                    $("#likecount").html(parseInt($("#likecount").html()) + 1);
                                    }
                                else{
                                    $("#like").html("Like");
                                    $("#likecount").html( parseInt($("#likecount").html()) - 1);
                                    }
                                },
                                error: function(rs, e) {
                                      alert(rs.responseText);
                                }
                          });
                    })
            </script>
    <!-- Comments show button -->
           <button class="btn btn-danger" type="button" id="CMSHOWbtn"
           data-toggle="collapse" data-target="#collapseComments" aria-expanded="false" aria-controls="collapseComments">
           Comments <div class="badge">{{ post.comments.all|length }}</div></button>
        <!-- team members show button -->
            <button class="btn btn-danger" type="button" id="TMSHOWbtn"
            data-toggle="collapse" data-target="#collapseTeam" aria-expanded="false" aria-controls="collapseTeam">
            Members <div class="badge">{{ post.member.all|length }}</div></button>
        </div>
    </div>

    <div class="container">
        <div class="collapse multi-collapse  postdetailstyle" id="collapseComments" >
            <br/><br/><div class="text-center"><h4>Leave a New Comment</h4></div><hr/>
            {% if user.is_authenticated %}

            <form class="form-group" action="{{ post.id }}/add-comment/" method="post">
                {% csrf_token %}
                {% for non_field_error in form_cm.non_field_errors %}
                    <p class="alert alert-danger">{{ non_field_error }}</p>
                {% endfor %}
                {% for field in form_cm %}
                    <div>
                        {{ field }}
                    {% for error in field.errors %}
                        <p class="alert alert-danger">{{ error }}</p>
                    {% endfor %}
                    </div>
                {% endfor %}
                <input type="submit" value="Comment" class="btn btn-light">
            </form>
            {% else %}
            <div class="alert alert-info">
            <button class="btn btn-light"><a href="{% url 'login' %}?next={{request.path}}">Please Login!</a></button></div>
            {% endif %}
            <br/><br/><div class="text-center"><h4>Recent Comments</h4></div><hr/>
            <div class="card card-body">
                {% if post.comments.all|length %}
                    {% for comment in post.comments.all %}
                    <div class="row" style="padding: 10px;">
                        <div class="picture-container">
                          <div class="profilepicsmall">
                              <img src="{{ comment.user.profile_pic.url }}" class="profilepicsmall" id="wizardPicturePreview" title=""/>
                          </div>
                      </div>
                      
                    <div class="usernameclass"><h3><a href="{% url 'accounts:profile-other' comment.user.user %}">@{{ comment.user.user }}</a></h3></div class="usernameclass">
                </div>
                    <div><h3><pre class="well well-lg">   {{ comment.text }}</pre></h3></div><br>
                    <hr/>
                    {% endfor %}
                {% else %}
                <div><h3><pre class="well well-lg">There is no Comments to show</pre></h3></div><br/>
                {% endif %}
            </div>
        </div>
        <div class="collapse multi-collapse  postdetailstyle" id="collapseTeam">
            <div class="card card-body">
                {% if post.member.all|length %}
                    {% for team_member in post.member.all %}
                    <div class="row" style="padding: 10px;">
                        <div class="picture-container">
                          <div class="profilepicsmall">
                              <img src="{{ team_member.user.profile_pic.url }}" class="profilepicsmall" id="wizardPicturePreview" title=""/>
                          </div>
                      </div>
                    <div class="usernameclass"><h3><a href="{% url 'accounts:profile-other' team_member.user.user %}">@{{ team_member.user.user }}</a></h3></div class="usernameclass">
                        <ul class="well well-lg">
                        {% for role in team_member.role.all %}
                            <li><div><h3><pre>{{ role }}</pre></h3></div><br></li>
                        {% endfor %}
                        </ul>
                    </div>
                    <hr/>
                    {% endfor %}
                {% else %}
                <div><h3><pre class="well well-lg">There is no members to show</pre></h3></div><br>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    <script>
        $(document).ready(function(){
            $("#TMSHOWbtn").click(function(){
                $("#collapseComments").collapse('hide');
            });
        });
        $(document).ready(function(){
            $("#CMSHOWbtn").click(function(){
                $("#collapseTeam").collapse('hide');
            });
        });
    </script>

    {% endif %}
{% else %}
    <p>this post is not available.</p>
{% endif %}
</div>
{% endblock %}